name: linuxwell
description: by Radek Pazdera
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown:    kramdown
pygments: true
paginate: 15
timezone:    UK/London
future:      true

# Details for the RSS feed generator
url:            'http://linuxwell.com'
author:         'Radek Pazdera'

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/
