name: broken.build
title: Broken Build
description: "by Radek Pazdera"
meta_description: "A blog about programming, mobile and tech in general."

markdown: kramdown
highligher: true
paginate: 15
timezone: UK/London
future:   true

# Details for the RSS feed generator
url:            'http://broken.build'
author:         'Radek Pazdera'

email:          'me@radek.io'
twitter:        'radekpazdera'
github:         'pazdera'
linkedin:       'pazdera'
gplus:          '+RadekPazdera'

disqus_shortname: linuxwell

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/

gems:
  - 'jekyll-paginate'
